version: '3.4'

services:
  calendarplanning.server:
    container_name: calendar_planning_api
    image: ${DOCKER_REGISTRY-}calendarplanningserver
    build:
      context: .
      dockerfile: CalendarPlanning/Server/Dockerfile
    ports:
        - 8002:80
    networks:
        - backend
    environment:
        - DB_FILE_LOCATION=/db
        - ADMIN_EMAIL=admin@example.com
        - ADMIN_PASSWORD=Admin!12
    volumes:
        - ./db:/db

networks:
  backend: